language: python
python: '3.6'
env:
  global:
  - FRONTEND_PATH=$TRAVIS_BUILD_DIR
  - DOCKER_PATH=$TRAVIS_BUILD_DIR/docker/release/Dockerfile
  - IMAGE_TAG=rakeshchoyal92/frontend:latest
services:
- docker
jobs:
  include:
  - stage: Build docker image
    if: branch = develop
    script:
    - docker build -t $IMAGE_TAG --build-arg LICENSE_FILE=Unity_lic.ulf -f $DOCKER_PATH
      $FRONTEND_PATH
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push $IMAGE_TAG
#before_install:
#- openssl aes-256-cbc -K $encrypted_1e6e54d37d34_key -iv $encrypted_1e6e54d37d34_iv
#  -in Unity_lic.ulf.enc -out Unity_lic.ulf -d
